name: TradeWatch
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.6
  path: ^1.8.0
  sqflite: ^2.0.2+1
  flutter_local_notifications: ^15.1.0+1
  intl: ^0.17.0
  timezone: ^0.9.2
  permission_handler: ^10.4.3
  flutter_timezone: ^1.0.7
  shared_preferences: ^2.0.10
  workmanager: ^0.5.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/CompanyData.db
